name = "tier-revealer"

pages_build_output_dir = "apps/web/.svelte-kit/cloudflare"

kv_namespaces = [
    { binding = "KV_NAMESPACE_RIOT_TOKENS", id = "66d349bfa38a43739e16793dc509b860" },
    { binding = "KV_NAMESPACE_AUTH_CHALLENGES", id = "8465fd92ae3b4afcba6946f662c770e0" }
]

[[d1_databases]]
binding = "D1_DB"
database_name = "tier-revealer"
database_id = "0ce8856f-b7cf-4170-ab59-fe4ebf781a6e"
