name: Build

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Install Playwright Browser(s)
        run: npx playwright install chromium --with-deps

      - run: npm run lint --workspaces --if-present
      - run: npm run build --workspaces --if-present
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          RIOT_SIGN_ON_CLIENT_SECRET: ${{ secrets.RIOT_SIGN_ON_CLIENT_SECRET }}
          PUBLIC_RIOT_SIGN_ON_CLIENT_ID: ${{ vars.PUBLIC_RIOT_SIGN_ON_CLIENT_ID }}
          PUBLIC_RIOT_SIGN_ON_REDIRECT_URI: ${{ vars.PUBLIC_RIOT_SIGN_ON_REDIRECT_URI }}
      - run: npm run test --workspaces --if-present
      - run: npm run check --workspaces --if-present

      - name: Migrate DB
        run: npx wrangler d1 migrations apply 'tier-revealer' --remote
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy
        run: npx wrangler pages deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
